/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppRole = { 'customer' : null } |
  { 'driver' : null };
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface CompanyEarnings {
  'totalCommission' : number,
  'totalDeposits' : number,
  'totalCompanyEarnings' : number,
}
export interface Coordinates { 'latitude' : number, 'longitude' : number }
export interface CostSummary { 'total' : number, 'details' : string }
export interface DriverEarnings {
  'driverId' : Principal,
  'totalHours' : number,
  'totalJobs' : bigint,
  'paymentBreakdown' : Array<PaymentBreakdown>,
  'totalEarnings' : number,
  'totalMileage' : number,
}
export interface DriverProfile {
  'driverId' : Principal,
  'stripeAccountId' : [] | [string],
  'name' : string,
  'driverCoordinates' : Coordinates,
  'carNumber' : string,
  'photo' : [] | [ExternalBlob],
}
export type ExternalBlob = Uint8Array;
export interface GeneralVehicleTag {
  'driverId' : bigint,
  'firingRange' : bigint,
  'carNumber' : string,
  'vehicleId' : bigint,
}
export interface LocationDetails {
  'dropoffCoordinates' : [] | [Coordinates],
  'pickupCoordinates' : [] | [Coordinates],
  'pickupAddress' : [] | [string],
  'dropoffAddress' : [] | [string],
}
export interface PaymentBreakdown {
  'mileagePay' : number,
  'depositShare' : number,
  'totalPay' : number,
  'companyCommission' : number,
  'hourlyPay' : number,
  'taxDeduction' : number,
  'commissionDeduction' : number,
}
export type PaymentStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'transferred' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export type StatusUpdate = { 'cancelled' : { 'reason' : string } } |
  { 'arrived' : { 'message' : string } } |
  { 'completed' : { 'summary' : CostSummary } } |
  { 'waiting' : { 'message' : string } } |
  { 'inProgress' : { 'message' : string } } |
  { 'enRoute' : { 'message' : string } } |
  { 'tripAccepted' : { 'message' : string } };
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface Trip {
  'startTime' : bigint,
  'driverId' : [] | [Principal],
  'duration' : [] | [number],
  'clientId' : Principal,
  'paymentStatus' : PaymentStatus,
  'endTime' : [] | [bigint],
  'specialRequests' : string,
  'tripId' : bigint,
  'totalCost' : [] | [number],
  'distance' : number,
  'translatorNeeded' : boolean,
  'endLocation' : [] | [Coordinates],
  'helpLoadingItems' : [] | [boolean],
  'tripCostCalculation' : [] | [TripCostCalculation],
  'startLocation' : Coordinates,
  'locationDetails' : LocationDetails,
  'statusUpdate' : [] | [StatusUpdate],
  'tripStatus' : TripStatus,
  'depositPaid' : boolean,
}
export interface TripCostCalculation {
  'durationCost' : number,
  'totalCost' : number,
  'deposit' : number,
  'companyCommission' : number,
  'mileageCost' : number,
  'baseCost' : number,
}
export type TripStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'accepted' : null } |
  { 'inProgress' : null };
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'userCoordinates' : Coordinates,
  'appRole' : AppRole,
  'isDriver' : boolean,
  'userId' : Principal,
  'profileImage' : [] | [ExternalBlob],
  'name' : string,
  'phoneNumber' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VideoMetadata {
  'title' : string,
  'description' : string,
  'filePath' : string,
  'videoType' : VideoType,
}
export type VideoType = { 'driverInstructional' : null } |
  { 'clientInstructional' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addVehicle' : ActorMethod<[GeneralVehicleTag], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateTotalDistance' : ActorMethod<[Principal], number>,
  'calculateTotalEarnings' : ActorMethod<[Principal], number>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createDepositCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createDriverStripeAccountId' : ActorMethod<[string], undefined>,
  'createFinalPaymentCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createTrip' : ActorMethod<[Trip], bigint>,
  'disconnectDriverStripeAccount' : ActorMethod<[], undefined>,
  'getAllDriverEarnings' : ActorMethod<[], Array<DriverEarnings>>,
  'getAllDriverProfilesWithPhotos' : ActorMethod<
    [],
    Array<[DriverProfile, [] | [ExternalBlob]]>
  >,
  'getAllDrivers' : ActorMethod<[], Array<DriverProfile>>,
  'getAllVideoMetadata' : ActorMethod<[], Array<VideoMetadata>>,
  'getCallerDriverProfile' : ActorMethod<[], [] | [DriverProfile]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClientTrips' : ActorMethod<[], Array<Trip>>,
  'getCompanyEarnings' : ActorMethod<[], CompanyEarnings>,
  'getDriver' : ActorMethod<[Principal], [] | [DriverProfile]>,
  'getDriverEarnings' : ActorMethod<[Principal], [] | [DriverEarnings]>,
  'getDriverPhoto' : ActorMethod<[Principal], [] | [ExternalBlob]>,
  'getDriverTrips' : ActorMethod<[], Array<Trip>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTotalCompletedJobs' : ActorMethod<[Principal], bigint>,
  'getTrip' : ActorMethod<[bigint], [] | [Trip]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideoMetadata' : ActorMethod<[string], [] | [VideoMetadata]>,
  'getVideosByType' : ActorMethod<[VideoType], Array<VideoMetadata>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveDriverProfile' : ActorMethod<[DriverProfile], undefined>,
  'saveProfileImage' : ActorMethod<[Principal, ExternalBlob], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateDriverEarnings' : ActorMethod<
    [Principal, PaymentBreakdown],
    undefined
  >,
  'updateHelpLoadingItems' : ActorMethod<[bigint, boolean], undefined>,
  'updatePaymentBreakdown' : ActorMethod<
    [Principal, PaymentBreakdown],
    undefined
  >,
  'updateTripPaymentStatus' : ActorMethod<[bigint, PaymentStatus], undefined>,
  'updateTripStatus' : ActorMethod<
    [bigint, TripStatus, [] | [StatusUpdate]],
    undefined
  >,
  'uploadDriverPhoto' : ActorMethod<[ExternalBlob], ExternalBlob>,
  'uploadVideoMetadata' : ActorMethod<[VideoMetadata], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];