/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const GeneralVehicleTag = IDL.Record({
  'driverId' : IDL.Nat,
  'firingRange' : IDL.Nat,
  'carNumber' : IDL.Text,
  'vehicleId' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'transferred' : IDL.Null,
});
export const Coordinates = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const TripCostCalculation = IDL.Record({
  'durationCost' : IDL.Float64,
  'totalCost' : IDL.Float64,
  'deposit' : IDL.Float64,
  'companyCommission' : IDL.Float64,
  'mileageCost' : IDL.Float64,
  'baseCost' : IDL.Float64,
});
export const LocationDetails = IDL.Record({
  'dropoffCoordinates' : IDL.Opt(Coordinates),
  'pickupCoordinates' : IDL.Opt(Coordinates),
  'pickupAddress' : IDL.Opt(IDL.Text),
  'dropoffAddress' : IDL.Opt(IDL.Text),
});
export const CostSummary = IDL.Record({
  'total' : IDL.Float64,
  'details' : IDL.Text,
});
export const StatusUpdate = IDL.Variant({
  'cancelled' : IDL.Record({ 'reason' : IDL.Text }),
  'arrived' : IDL.Record({ 'message' : IDL.Text }),
  'completed' : IDL.Record({ 'summary' : CostSummary }),
  'waiting' : IDL.Record({ 'message' : IDL.Text }),
  'inProgress' : IDL.Record({ 'message' : IDL.Text }),
  'enRoute' : IDL.Record({ 'message' : IDL.Text }),
  'tripAccepted' : IDL.Record({ 'message' : IDL.Text }),
});
export const TripStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'accepted' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Trip = IDL.Record({
  'startTime' : IDL.Int,
  'driverId' : IDL.Opt(IDL.Principal),
  'duration' : IDL.Opt(IDL.Float64),
  'clientId' : IDL.Principal,
  'paymentStatus' : PaymentStatus,
  'endTime' : IDL.Opt(IDL.Int),
  'specialRequests' : IDL.Text,
  'tripId' : IDL.Nat,
  'totalCost' : IDL.Opt(IDL.Float64),
  'distance' : IDL.Float64,
  'translatorNeeded' : IDL.Bool,
  'endLocation' : IDL.Opt(Coordinates),
  'helpLoadingItems' : IDL.Opt(IDL.Bool),
  'tripCostCalculation' : IDL.Opt(TripCostCalculation),
  'startLocation' : Coordinates,
  'locationDetails' : LocationDetails,
  'statusUpdate' : IDL.Opt(StatusUpdate),
  'tripStatus' : TripStatus,
  'depositPaid' : IDL.Bool,
});
export const PaymentBreakdown = IDL.Record({
  'mileagePay' : IDL.Float64,
  'depositShare' : IDL.Float64,
  'totalPay' : IDL.Float64,
  'companyCommission' : IDL.Float64,
  'hourlyPay' : IDL.Float64,
  'taxDeduction' : IDL.Float64,
  'commissionDeduction' : IDL.Float64,
});
export const DriverEarnings = IDL.Record({
  'driverId' : IDL.Principal,
  'totalHours' : IDL.Float64,
  'totalJobs' : IDL.Nat,
  'paymentBreakdown' : IDL.Vec(PaymentBreakdown),
  'totalEarnings' : IDL.Float64,
  'totalMileage' : IDL.Float64,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const DriverProfile = IDL.Record({
  'driverId' : IDL.Principal,
  'stripeAccountId' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'driverCoordinates' : Coordinates,
  'carNumber' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
});
export const VideoType = IDL.Variant({
  'driverInstructional' : IDL.Null,
  'clientInstructional' : IDL.Null,
});
export const VideoMetadata = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'filePath' : IDL.Text,
  'videoType' : VideoType,
});
export const AppRole = IDL.Variant({
  'customer' : IDL.Null,
  'driver' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'userCoordinates' : Coordinates,
  'appRole' : AppRole,
  'isDriver' : IDL.Bool,
  'userId' : IDL.Principal,
  'profileImage' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const CompanyEarnings = IDL.Record({
  'totalCommission' : IDL.Float64,
  'totalDeposits' : IDL.Float64,
  'totalCompanyEarnings' : IDL.Float64,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addVehicle' : IDL.Func([GeneralVehicleTag], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateTotalDistance' : IDL.Func(
      [IDL.Principal],
      [IDL.Float64],
      ['query'],
    ),
  'calculateTotalEarnings' : IDL.Func(
      [IDL.Principal],
      [IDL.Float64],
      ['query'],
    ),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createDepositCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createDriverStripeAccountId' : IDL.Func([IDL.Text], [], []),
  'createFinalPaymentCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createTrip' : IDL.Func([Trip], [IDL.Nat], []),
  'disconnectDriverStripeAccount' : IDL.Func([], [], []),
  'getAllDriverEarnings' : IDL.Func([], [IDL.Vec(DriverEarnings)], ['query']),
  'getAllDriverProfilesWithPhotos' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(DriverProfile, IDL.Opt(ExternalBlob)))],
      ['query'],
    ),
  'getAllDrivers' : IDL.Func([], [IDL.Vec(DriverProfile)], ['query']),
  'getAllVideoMetadata' : IDL.Func([], [IDL.Vec(VideoMetadata)], ['query']),
  'getCallerDriverProfile' : IDL.Func([], [IDL.Opt(DriverProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClientTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
  'getCompanyEarnings' : IDL.Func([], [CompanyEarnings], ['query']),
  'getDriver' : IDL.Func([IDL.Principal], [IDL.Opt(DriverProfile)], ['query']),
  'getDriverEarnings' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(DriverEarnings)],
      ['query'],
    ),
  'getDriverPhoto' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(ExternalBlob)],
      ['query'],
    ),
  'getDriverTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTotalCompletedJobs' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getTrip' : IDL.Func([IDL.Nat], [IDL.Opt(Trip)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideoMetadata' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(VideoMetadata)],
      ['query'],
    ),
  'getVideosByType' : IDL.Func(
      [VideoType],
      [IDL.Vec(VideoMetadata)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveDriverProfile' : IDL.Func([DriverProfile], [], []),
  'saveProfileImage' : IDL.Func([IDL.Principal, ExternalBlob], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateDriverEarnings' : IDL.Func([IDL.Principal, PaymentBreakdown], [], []),
  'updateHelpLoadingItems' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'updatePaymentBreakdown' : IDL.Func(
      [IDL.Principal, PaymentBreakdown],
      [],
      [],
    ),
  'updateTripPaymentStatus' : IDL.Func([IDL.Nat, PaymentStatus], [], []),
  'updateTripStatus' : IDL.Func(
      [IDL.Nat, TripStatus, IDL.Opt(StatusUpdate)],
      [],
      [],
    ),
  'uploadDriverPhoto' : IDL.Func([ExternalBlob], [ExternalBlob], []),
  'uploadVideoMetadata' : IDL.Func([VideoMetadata], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const GeneralVehicleTag = IDL.Record({
    'driverId' : IDL.Nat,
    'firingRange' : IDL.Nat,
    'carNumber' : IDL.Text,
    'vehicleId' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'transferred' : IDL.Null,
  });
  const Coordinates = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const TripCostCalculation = IDL.Record({
    'durationCost' : IDL.Float64,
    'totalCost' : IDL.Float64,
    'deposit' : IDL.Float64,
    'companyCommission' : IDL.Float64,
    'mileageCost' : IDL.Float64,
    'baseCost' : IDL.Float64,
  });
  const LocationDetails = IDL.Record({
    'dropoffCoordinates' : IDL.Opt(Coordinates),
    'pickupCoordinates' : IDL.Opt(Coordinates),
    'pickupAddress' : IDL.Opt(IDL.Text),
    'dropoffAddress' : IDL.Opt(IDL.Text),
  });
  const CostSummary = IDL.Record({
    'total' : IDL.Float64,
    'details' : IDL.Text,
  });
  const StatusUpdate = IDL.Variant({
    'cancelled' : IDL.Record({ 'reason' : IDL.Text }),
    'arrived' : IDL.Record({ 'message' : IDL.Text }),
    'completed' : IDL.Record({ 'summary' : CostSummary }),
    'waiting' : IDL.Record({ 'message' : IDL.Text }),
    'inProgress' : IDL.Record({ 'message' : IDL.Text }),
    'enRoute' : IDL.Record({ 'message' : IDL.Text }),
    'tripAccepted' : IDL.Record({ 'message' : IDL.Text }),
  });
  const TripStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'accepted' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Trip = IDL.Record({
    'startTime' : IDL.Int,
    'driverId' : IDL.Opt(IDL.Principal),
    'duration' : IDL.Opt(IDL.Float64),
    'clientId' : IDL.Principal,
    'paymentStatus' : PaymentStatus,
    'endTime' : IDL.Opt(IDL.Int),
    'specialRequests' : IDL.Text,
    'tripId' : IDL.Nat,
    'totalCost' : IDL.Opt(IDL.Float64),
    'distance' : IDL.Float64,
    'translatorNeeded' : IDL.Bool,
    'endLocation' : IDL.Opt(Coordinates),
    'helpLoadingItems' : IDL.Opt(IDL.Bool),
    'tripCostCalculation' : IDL.Opt(TripCostCalculation),
    'startLocation' : Coordinates,
    'locationDetails' : LocationDetails,
    'statusUpdate' : IDL.Opt(StatusUpdate),
    'tripStatus' : TripStatus,
    'depositPaid' : IDL.Bool,
  });
  const PaymentBreakdown = IDL.Record({
    'mileagePay' : IDL.Float64,
    'depositShare' : IDL.Float64,
    'totalPay' : IDL.Float64,
    'companyCommission' : IDL.Float64,
    'hourlyPay' : IDL.Float64,
    'taxDeduction' : IDL.Float64,
    'commissionDeduction' : IDL.Float64,
  });
  const DriverEarnings = IDL.Record({
    'driverId' : IDL.Principal,
    'totalHours' : IDL.Float64,
    'totalJobs' : IDL.Nat,
    'paymentBreakdown' : IDL.Vec(PaymentBreakdown),
    'totalEarnings' : IDL.Float64,
    'totalMileage' : IDL.Float64,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const DriverProfile = IDL.Record({
    'driverId' : IDL.Principal,
    'stripeAccountId' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'driverCoordinates' : Coordinates,
    'carNumber' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
  });
  const VideoType = IDL.Variant({
    'driverInstructional' : IDL.Null,
    'clientInstructional' : IDL.Null,
  });
  const VideoMetadata = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'filePath' : IDL.Text,
    'videoType' : VideoType,
  });
  const AppRole = IDL.Variant({ 'customer' : IDL.Null, 'driver' : IDL.Null });
  const UserProfile = IDL.Record({
    'userCoordinates' : Coordinates,
    'appRole' : AppRole,
    'isDriver' : IDL.Bool,
    'userId' : IDL.Principal,
    'profileImage' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const CompanyEarnings = IDL.Record({
    'totalCommission' : IDL.Float64,
    'totalDeposits' : IDL.Float64,
    'totalCompanyEarnings' : IDL.Float64,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addVehicle' : IDL.Func([GeneralVehicleTag], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateTotalDistance' : IDL.Func(
        [IDL.Principal],
        [IDL.Float64],
        ['query'],
      ),
    'calculateTotalEarnings' : IDL.Func(
        [IDL.Principal],
        [IDL.Float64],
        ['query'],
      ),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createDepositCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createDriverStripeAccountId' : IDL.Func([IDL.Text], [], []),
    'createFinalPaymentCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createTrip' : IDL.Func([Trip], [IDL.Nat], []),
    'disconnectDriverStripeAccount' : IDL.Func([], [], []),
    'getAllDriverEarnings' : IDL.Func([], [IDL.Vec(DriverEarnings)], ['query']),
    'getAllDriverProfilesWithPhotos' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(DriverProfile, IDL.Opt(ExternalBlob)))],
        ['query'],
      ),
    'getAllDrivers' : IDL.Func([], [IDL.Vec(DriverProfile)], ['query']),
    'getAllVideoMetadata' : IDL.Func([], [IDL.Vec(VideoMetadata)], ['query']),
    'getCallerDriverProfile' : IDL.Func(
        [],
        [IDL.Opt(DriverProfile)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClientTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
    'getCompanyEarnings' : IDL.Func([], [CompanyEarnings], ['query']),
    'getDriver' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(DriverProfile)],
        ['query'],
      ),
    'getDriverEarnings' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(DriverEarnings)],
        ['query'],
      ),
    'getDriverPhoto' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ExternalBlob)],
        ['query'],
      ),
    'getDriverTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTotalCompletedJobs' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getTrip' : IDL.Func([IDL.Nat], [IDL.Opt(Trip)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideoMetadata' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(VideoMetadata)],
        ['query'],
      ),
    'getVideosByType' : IDL.Func(
        [VideoType],
        [IDL.Vec(VideoMetadata)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveDriverProfile' : IDL.Func([DriverProfile], [], []),
    'saveProfileImage' : IDL.Func([IDL.Principal, ExternalBlob], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateDriverEarnings' : IDL.Func(
        [IDL.Principal, PaymentBreakdown],
        [],
        [],
      ),
    'updateHelpLoadingItems' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'updatePaymentBreakdown' : IDL.Func(
        [IDL.Principal, PaymentBreakdown],
        [],
        [],
      ),
    'updateTripPaymentStatus' : IDL.Func([IDL.Nat, PaymentStatus], [], []),
    'updateTripStatus' : IDL.Func(
        [IDL.Nat, TripStatus, IDL.Opt(StatusUpdate)],
        [],
        [],
      ),
    'uploadDriverPhoto' : IDL.Func([ExternalBlob], [ExternalBlob], []),
    'uploadVideoMetadata' : IDL.Func([VideoMetadata], [], []),
  });
};

export const init = ({ IDL }) => { return []; };