/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Trip {
    startTime: bigint;
    miles?: number;
    driverId?: Principal;
    duration?: number;
    clientId: Principal;
    paymentStatus: PaymentStatus;
    endTime?: bigint;
    specialRequests: string;
    tripId: bigint;
    totalCost?: number;
    distance: number;
    translatorNeeded: boolean;
    endLocation?: Coordinates;
    helpLoadingItems?: boolean;
    tripCostCalculation?: TripCostCalculation;
    startLocation: Coordinates;
    locationDetails: LocationDetails;
    statusUpdate?: StatusUpdate;
    tripStatus: TripStatus;
    depositPaid: boolean;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Coordinates {
    latitude: number;
    longitude: number;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type StatusUpdate = {
    __kind__: "cancelled";
    cancelled: {
        reason: string;
    };
} | {
    __kind__: "arrived";
    arrived: {
        message: string;
    };
} | {
    __kind__: "completed";
    completed: {
        summary: CostSummary;
    };
} | {
    __kind__: "waiting";
    waiting: {
        message: string;
    };
} | {
    __kind__: "inProgress";
    inProgress: {
        message: string;
    };
} | {
    __kind__: "enRoute";
    enRoute: {
        message: string;
    };
} | {
    __kind__: "tripAccepted";
    tripAccepted: {
        message: string;
    };
};
export interface DriverProfile {
    driverId: Principal;
    stripeAccountId?: string;
    name: string;
    driverCoordinates: Coordinates;
    carNumber: string;
    photo?: ExternalBlob;
}
export interface CompanyEarnings {
    totalCommission: number;
    totalDeposits: number;
    totalCompanyEarnings: number;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface PaymentBreakdown {
    mileagePay: number;
    depositShare: number;
    totalPay: number;
    companyCommission: number;
    hourlyPay: number;
    taxDeduction: number;
    commissionDeduction: number;
}
export interface CostSummary {
    total: number;
    details: string;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface TripCostCalculation {
    durationCost: number;
    totalCost: number;
    deposit: number;
    companyCommission: number;
    mileageCost: number;
    baseCost: number;
}
export interface DriverEarnings {
    driverId: Principal;
    totalHours: number;
    totalJobs: bigint;
    paymentBreakdown: Array<PaymentBreakdown>;
    totalEarnings: number;
    totalMileage: number;
}
export interface LocationDetails {
    dropoffCoordinates?: Coordinates;
    pickupCoordinates?: Coordinates;
    pickupAddress?: string;
    dropoffAddress?: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface GeneralVehicleTag {
    driverId: bigint;
    firingRange: bigint;
    carNumber: string;
    vehicleId: bigint;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface VideoMetadata {
    title: string;
    description: string;
    filePath: string;
    videoType: VideoType;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    userCoordinates: Coordinates;
    appRole: AppRole;
    isDriver: boolean;
    userId: Principal;
    profileImage?: ExternalBlob;
    name: string;
    phoneNumber: string;
}
export enum AppRole {
    customer = "customer",
    driver = "driver"
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum PaymentStatus {
    pending = "pending",
    paid = "paid",
    transferred = "transferred"
}
export enum TripStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    accepted = "accepted",
    inProgress = "inProgress"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VideoType {
    driverInstructional = "driverInstructional",
    clientInstructional = "clientInstructional"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addVehicle(vehicle: GeneralVehicleTag): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    calculateTotalDistance(driverId: Principal): Promise<number>;
    calculateTotalEarnings(driverId: Principal): Promise<number>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createDepositCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createDriverStripeAccountId(stripeAccountId: string): Promise<void>;
    createFinalPaymentCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createTrip(trip: Trip): Promise<bigint>;
    disconnectDriverStripeAccount(): Promise<void>;
    getAllDriverEarnings(): Promise<Array<DriverEarnings>>;
    getAllDriverProfilesWithPhotos(): Promise<Array<[DriverProfile, ExternalBlob | null]>>;
    getAllDrivers(): Promise<Array<DriverProfile>>;
    getAllVideoMetadata(): Promise<Array<VideoMetadata>>;
    getCallerDriverProfile(): Promise<DriverProfile | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClientTrips(): Promise<Array<Trip>>;
    getCompanyEarnings(): Promise<CompanyEarnings>;
    getDriver(driverId: Principal): Promise<DriverProfile | null>;
    getDriverEarnings(driverId: Principal): Promise<DriverEarnings | null>;
    getDriverPhoto(driverId: Principal): Promise<ExternalBlob | null>;
    getDriverTrips(): Promise<Array<Trip>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getTotalCompletedJobs(driverId: Principal): Promise<bigint>;
    getTrip(tripId: bigint): Promise<Trip | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVideoMetadata(title: string): Promise<VideoMetadata | null>;
    getVideosByType(videoType: VideoType): Promise<Array<VideoMetadata>>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    requestApproval(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveDriverProfile(profile: DriverProfile): Promise<void>;
    saveProfileImage(userId: Principal, image: ExternalBlob): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateDriverEarnings(driverId: Principal, paymentBreakdown: PaymentBreakdown): Promise<void>;
    updateHelpLoadingItems(tripId: bigint, helpLoading: boolean): Promise<void>;
    updatePaymentBreakdown(driverId: Principal, newPaymentBreakdown: PaymentBreakdown): Promise<void>;
    updateTripMiles(tripId: bigint, miles: number): Promise<void>;
    updateTripPaymentStatus(tripId: bigint, newStatus: PaymentStatus): Promise<void>;
    updateTripStatus(tripId: bigint, newStatus: TripStatus, statusUpdate: StatusUpdate | null): Promise<void>;
    uploadDriverPhoto(photo: ExternalBlob): Promise<ExternalBlob>;
    uploadVideoMetadata(metadata: VideoMetadata): Promise<void>;
}
import type { AppRole as _AppRole, ApprovalStatus as _ApprovalStatus, Coordinates as _Coordinates, CostSummary as _CostSummary, DriverEarnings as _DriverEarnings, DriverProfile as _DriverProfile, ExternalBlob as _ExternalBlob, LocationDetails as _LocationDetails, PaymentStatus as _PaymentStatus, StatusUpdate as _StatusUpdate, StripeSessionStatus as _StripeSessionStatus, Trip as _Trip, TripCostCalculation as _TripCostCalculation, TripStatus as _TripStatus, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole, VideoMetadata as _VideoMetadata, VideoType as _VideoType, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addVehicle(arg0: GeneralVehicleTag): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addVehicle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVehicle(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async calculateTotalDistance(arg0: Principal): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateTotalDistance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateTotalDistance(arg0);
            return result;
        }
    }
    async calculateTotalEarnings(arg0: Principal): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateTotalEarnings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateTotalEarnings(arg0);
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createDepositCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createDepositCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDepositCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createDriverStripeAccountId(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createDriverStripeAccountId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDriverStripeAccountId(arg0);
            return result;
        }
    }
    async createFinalPaymentCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createFinalPaymentCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFinalPaymentCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createTrip(arg0: Trip): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTrip(to_candid_Trip_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTrip(to_candid_Trip_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async disconnectDriverStripeAccount(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.disconnectDriverStripeAccount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.disconnectDriverStripeAccount();
            return result;
        }
    }
    async getAllDriverEarnings(): Promise<Array<DriverEarnings>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDriverEarnings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDriverEarnings();
            return result;
        }
    }
    async getAllDriverProfilesWithPhotos(): Promise<Array<[DriverProfile, ExternalBlob | null]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDriverProfilesWithPhotos();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDriverProfilesWithPhotos();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDrivers(): Promise<Array<DriverProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDrivers();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDrivers();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllVideoMetadata(): Promise<Array<VideoMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVideoMetadata();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVideoMetadata();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerDriverProfile(): Promise<DriverProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerDriverProfile();
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerDriverProfile();
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClientTrips(): Promise<Array<Trip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClientTrips();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClientTrips();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompanyEarnings(): Promise<CompanyEarnings> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompanyEarnings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompanyEarnings();
            return result;
        }
    }
    async getDriver(arg0: Principal): Promise<DriverProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDriver(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDriver(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDriverEarnings(arg0: Principal): Promise<DriverEarnings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDriverEarnings(arg0);
                return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDriverEarnings(arg0);
            return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDriverPhoto(arg0: Principal): Promise<ExternalBlob | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDriverPhoto(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDriverPhoto(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDriverTrips(): Promise<Array<Trip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDriverTrips();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDriverTrips();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalCompletedJobs(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalCompletedJobs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalCompletedJobs(arg0);
            return result;
        }
    }
    async getTrip(arg0: bigint): Promise<Trip | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrip(arg0);
                return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrip(arg0);
            return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideoMetadata(arg0: string): Promise<VideoMetadata | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideoMetadata(arg0);
                return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideoMetadata(arg0);
            return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideosByType(arg0: VideoType): Promise<Array<VideoMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideosByType(to_candid_VideoType_n64(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideosByType(to_candid_VideoType_n64(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n71(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n71(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveDriverProfile(arg0: DriverProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDriverProfile(await to_candid_DriverProfile_n76(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDriverProfile(await to_candid_DriverProfile_n76(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveProfileImage(arg0: Principal, arg1: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProfileImage(arg0, await to_candid_ExternalBlob_n75(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProfileImage(arg0, await to_candid_ExternalBlob_n75(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n78(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n78(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateDriverEarnings(arg0: Principal, arg1: PaymentBreakdown): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDriverEarnings(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDriverEarnings(arg0, arg1);
            return result;
        }
    }
    async updateHelpLoadingItems(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHelpLoadingItems(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHelpLoadingItems(arg0, arg1);
            return result;
        }
    }
    async updatePaymentBreakdown(arg0: Principal, arg1: PaymentBreakdown): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePaymentBreakdown(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePaymentBreakdown(arg0, arg1);
            return result;
        }
    }
    async updateTripMiles(arg0: bigint, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTripMiles(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTripMiles(arg0, arg1);
            return result;
        }
    }
    async updateTripPaymentStatus(arg0: bigint, arg1: PaymentStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTripPaymentStatus(arg0, to_candid_PaymentStatus_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTripPaymentStatus(arg0, to_candid_PaymentStatus_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTripStatus(arg0: bigint, arg1: TripStatus, arg2: StatusUpdate | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTripStatus(arg0, to_candid_TripStatus_n18(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n80(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTripStatus(arg0, to_candid_TripStatus_n18(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n80(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async uploadDriverPhoto(arg0: ExternalBlob): Promise<ExternalBlob> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadDriverPhoto(await to_candid_ExternalBlob_n75(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ExternalBlob_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadDriverPhoto(await to_candid_ExternalBlob_n75(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ExternalBlob_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async uploadVideoMetadata(arg0: VideoMetadata): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadVideoMetadata(to_candid_VideoMetadata_n81(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadVideoMetadata(to_candid_VideoMetadata_n81(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AppRole_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppRole): AppRole {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_ApprovalStatus_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n70(_uploadFile, _downloadFile, value);
}
async function from_candid_DriverProfile_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DriverProfile): Promise<DriverProfile> {
    return await from_candid_record_n23(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_LocationDetails_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LocationDetails): LocationDetails {
    return from_candid_record_n52(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_StatusUpdate_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StatusUpdate): StatusUpdate {
    return from_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n60(_uploadFile, _downloadFile, value);
}
function from_candid_TripStatus_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TripStatus): TripStatus {
    return from_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function from_candid_Trip_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Trip): Trip {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n68(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_VideoMetadata_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoMetadata): VideoMetadata {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_VideoType_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoType): VideoType {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n26(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DriverProfile]): Promise<DriverProfile | null> {
    return value.length === 0 ? null : await from_candid_DriverProfile_n22(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Coordinates]): Coordinates | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TripCostCalculation]): TripCostCalculation | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StatusUpdate]): StatusUpdate | null {
    return value.length === 0 ? null : from_candid_StatusUpdate_n54(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DriverEarnings]): DriverEarnings | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Trip]): Trip | null {
    return value.length === 0 ? null : from_candid_Trip_n42(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VideoMetadata]): VideoMetadata | null {
    return value.length === 0 ? null : from_candid_VideoMetadata_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    driverId: Principal;
    stripeAccountId: [] | [string];
    name: string;
    driverCoordinates: _Coordinates;
    carNumber: string;
    photo: [] | [_ExternalBlob];
}): Promise<{
    driverId: Principal;
    stripeAccountId?: string;
    name: string;
    driverCoordinates: Coordinates;
    carNumber: string;
    photo?: ExternalBlob;
}> {
    return {
        driverId: value.driverId,
        stripeAccountId: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.stripeAccountId)),
        name: value.name,
        driverCoordinates: value.driverCoordinates,
        carNumber: value.carNumber,
        photo: record_opt_to_undefined(await from_candid_opt_n25(_uploadFile, _downloadFile, value.photo))
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    description: string;
    filePath: string;
    videoType: _VideoType;
}): {
    title: string;
    description: string;
    filePath: string;
    videoType: VideoType;
} {
    return {
        title: value.title,
        description: value.description,
        filePath: value.filePath,
        videoType: from_candid_VideoType_n31(_uploadFile, _downloadFile, value.videoType)
    };
}
async function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userCoordinates: _Coordinates;
    appRole: _AppRole;
    isDriver: boolean;
    userId: Principal;
    profileImage: [] | [_ExternalBlob];
    name: string;
    phoneNumber: string;
}): Promise<{
    userCoordinates: Coordinates;
    appRole: AppRole;
    isDriver: boolean;
    userId: Principal;
    profileImage?: ExternalBlob;
    name: string;
    phoneNumber: string;
}> {
    return {
        userCoordinates: value.userCoordinates,
        appRole: from_candid_AppRole_n37(_uploadFile, _downloadFile, value.appRole),
        isDriver: value.isDriver,
        userId: value.userId,
        profileImage: record_opt_to_undefined(await from_candid_opt_n25(_uploadFile, _downloadFile, value.profileImage)),
        name: value.name,
        phoneNumber: value.phoneNumber
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: bigint;
    miles: [] | [number];
    driverId: [] | [Principal];
    duration: [] | [number];
    clientId: Principal;
    paymentStatus: _PaymentStatus;
    endTime: [] | [bigint];
    specialRequests: string;
    tripId: bigint;
    totalCost: [] | [number];
    distance: number;
    translatorNeeded: boolean;
    endLocation: [] | [_Coordinates];
    helpLoadingItems: [] | [boolean];
    tripCostCalculation: [] | [_TripCostCalculation];
    startLocation: _Coordinates;
    locationDetails: _LocationDetails;
    statusUpdate: [] | [_StatusUpdate];
    tripStatus: _TripStatus;
    depositPaid: boolean;
}): {
    startTime: bigint;
    miles?: number;
    driverId?: Principal;
    duration?: number;
    clientId: Principal;
    paymentStatus: PaymentStatus;
    endTime?: bigint;
    specialRequests: string;
    tripId: bigint;
    totalCost?: number;
    distance: number;
    translatorNeeded: boolean;
    endLocation?: Coordinates;
    helpLoadingItems?: boolean;
    tripCostCalculation?: TripCostCalculation;
    startLocation: Coordinates;
    locationDetails: LocationDetails;
    statusUpdate?: StatusUpdate;
    tripStatus: TripStatus;
    depositPaid: boolean;
} {
    return {
        startTime: value.startTime,
        miles: record_opt_to_undefined(from_candid_opt_n44(_uploadFile, _downloadFile, value.miles)),
        driverId: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.driverId)),
        duration: record_opt_to_undefined(from_candid_opt_n44(_uploadFile, _downloadFile, value.duration)),
        clientId: value.clientId,
        paymentStatus: from_candid_PaymentStatus_n46(_uploadFile, _downloadFile, value.paymentStatus),
        endTime: record_opt_to_undefined(from_candid_opt_n48(_uploadFile, _downloadFile, value.endTime)),
        specialRequests: value.specialRequests,
        tripId: value.tripId,
        totalCost: record_opt_to_undefined(from_candid_opt_n44(_uploadFile, _downloadFile, value.totalCost)),
        distance: value.distance,
        translatorNeeded: value.translatorNeeded,
        endLocation: record_opt_to_undefined(from_candid_opt_n49(_uploadFile, _downloadFile, value.endLocation)),
        helpLoadingItems: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.helpLoadingItems)),
        tripCostCalculation: record_opt_to_undefined(from_candid_opt_n50(_uploadFile, _downloadFile, value.tripCostCalculation)),
        startLocation: value.startLocation,
        locationDetails: from_candid_LocationDetails_n51(_uploadFile, _downloadFile, value.locationDetails),
        statusUpdate: record_opt_to_undefined(from_candid_opt_n53(_uploadFile, _downloadFile, value.statusUpdate)),
        tripStatus: from_candid_TripStatus_n56(_uploadFile, _downloadFile, value.tripStatus),
        depositPaid: value.depositPaid
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dropoffCoordinates: [] | [_Coordinates];
    pickupCoordinates: [] | [_Coordinates];
    pickupAddress: [] | [string];
    dropoffAddress: [] | [string];
}): {
    dropoffCoordinates?: Coordinates;
    pickupCoordinates?: Coordinates;
    pickupAddress?: string;
    dropoffAddress?: string;
} {
    return {
        dropoffCoordinates: record_opt_to_undefined(from_candid_opt_n49(_uploadFile, _downloadFile, value.dropoffCoordinates)),
        pickupCoordinates: record_opt_to_undefined(from_candid_opt_n49(_uploadFile, _downloadFile, value.pickupCoordinates)),
        pickupAddress: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.pickupAddress)),
        dropoffAddress: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.dropoffAddress))
    };
}
function from_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n69(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
async function from_candid_tuple_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_DriverProfile, [] | [_ExternalBlob]]): Promise<[DriverProfile, ExternalBlob | null]> {
    return [
        await from_candid_DriverProfile_n22(_uploadFile, _downloadFile, value[0]),
        await from_candid_opt_n25(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    driverInstructional: null;
} | {
    clientInstructional: null;
}): VideoType {
    return "driverInstructional" in value ? VideoType.driverInstructional : "clientInstructional" in value ? VideoType.clientInstructional : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customer: null;
} | {
    driver: null;
}): AppRole {
    return "customer" in value ? AppRole.customer : "driver" in value ? AppRole.driver : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
} | {
    transferred: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "paid" in value ? PaymentStatus.paid : "transferred" in value ? PaymentStatus.transferred : value;
}
function from_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: {
        reason: string;
    };
} | {
    arrived: {
        message: string;
    };
} | {
    completed: {
        summary: _CostSummary;
    };
} | {
    waiting: {
        message: string;
    };
} | {
    inProgress: {
        message: string;
    };
} | {
    enRoute: {
        message: string;
    };
} | {
    tripAccepted: {
        message: string;
    };
}): {
    __kind__: "cancelled";
    cancelled: {
        reason: string;
    };
} | {
    __kind__: "arrived";
    arrived: {
        message: string;
    };
} | {
    __kind__: "completed";
    completed: {
        summary: CostSummary;
    };
} | {
    __kind__: "waiting";
    waiting: {
        message: string;
    };
} | {
    __kind__: "inProgress";
    inProgress: {
        message: string;
    };
} | {
    __kind__: "enRoute";
    enRoute: {
        message: string;
    };
} | {
    __kind__: "tripAccepted";
    tripAccepted: {
        message: string;
    };
} {
    return "cancelled" in value ? {
        __kind__: "cancelled",
        cancelled: value.cancelled
    } : "arrived" in value ? {
        __kind__: "arrived",
        arrived: value.arrived
    } : "completed" in value ? {
        __kind__: "completed",
        completed: value.completed
    } : "waiting" in value ? {
        __kind__: "waiting",
        waiting: value.waiting
    } : "inProgress" in value ? {
        __kind__: "inProgress",
        inProgress: value.inProgress
    } : "enRoute" in value ? {
        __kind__: "enRoute",
        enRoute: value.enRoute
    } : "tripAccepted" in value ? {
        __kind__: "tripAccepted",
        tripAccepted: value.tripAccepted
    } : value;
}
function from_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    accepted: null;
} | {
    inProgress: null;
}): TripStatus {
    return "cancelled" in value ? TripStatus.cancelled : "pending" in value ? TripStatus.pending : "completed" in value ? TripStatus.completed : "accepted" in value ? TripStatus.accepted : "inProgress" in value ? TripStatus.inProgress : value;
}
function from_candid_variant_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n61(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
async function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_DriverProfile, [] | [_ExternalBlob]]>): Promise<Array<[DriverProfile, ExternalBlob | null]>> {
    return await Promise.all(value.map(async (x)=>await from_candid_tuple_n21(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DriverProfile>): Promise<Array<DriverProfile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_DriverProfile_n22(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VideoMetadata>): Array<VideoMetadata> {
    return value.map((x)=>from_candid_VideoMetadata_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Trip>): Array<Trip> {
    return value.map((x)=>from_candid_Trip_n42(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n67(_uploadFile, _downloadFile, x));
}
function to_candid_AppRole_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): _AppRole {
    return to_candid_variant_n74(_uploadFile, _downloadFile, value);
}
function to_candid_ApprovalStatus_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n79(_uploadFile, _downloadFile, value);
}
async function to_candid_DriverProfile_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DriverProfile): Promise<_DriverProfile> {
    return await to_candid_record_n77(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_LocationDetails_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LocationDetails): _LocationDetails {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): _PaymentStatus {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_StatusUpdate_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StatusUpdate): _StatusUpdate {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_TripStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TripStatus): _TripStatus {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_Trip_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Trip): _Trip {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n72(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_VideoMetadata_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VideoMetadata): _VideoMetadata {
    return to_candid_record_n82(_uploadFile, _downloadFile, value);
}
function to_candid_VideoType_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VideoType): _VideoType {
    return to_candid_variant_n65(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StatusUpdate | null): [] | [_StatusUpdate] {
    return value === null ? candid_none() : candid_some(to_candid_StatusUpdate_n16(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: bigint;
    miles?: number;
    driverId?: Principal;
    duration?: number;
    clientId: Principal;
    paymentStatus: PaymentStatus;
    endTime?: bigint;
    specialRequests: string;
    tripId: bigint;
    totalCost?: number;
    distance: number;
    translatorNeeded: boolean;
    endLocation?: Coordinates;
    helpLoadingItems?: boolean;
    tripCostCalculation?: TripCostCalculation;
    startLocation: Coordinates;
    locationDetails: LocationDetails;
    statusUpdate?: StatusUpdate;
    tripStatus: TripStatus;
    depositPaid: boolean;
}): {
    startTime: bigint;
    miles: [] | [number];
    driverId: [] | [Principal];
    duration: [] | [number];
    clientId: Principal;
    paymentStatus: _PaymentStatus;
    endTime: [] | [bigint];
    specialRequests: string;
    tripId: bigint;
    totalCost: [] | [number];
    distance: number;
    translatorNeeded: boolean;
    endLocation: [] | [_Coordinates];
    helpLoadingItems: [] | [boolean];
    tripCostCalculation: [] | [_TripCostCalculation];
    startLocation: _Coordinates;
    locationDetails: _LocationDetails;
    statusUpdate: [] | [_StatusUpdate];
    tripStatus: _TripStatus;
    depositPaid: boolean;
} {
    return {
        startTime: value.startTime,
        miles: value.miles ? candid_some(value.miles) : candid_none(),
        driverId: value.driverId ? candid_some(value.driverId) : candid_none(),
        duration: value.duration ? candid_some(value.duration) : candid_none(),
        clientId: value.clientId,
        paymentStatus: to_candid_PaymentStatus_n12(_uploadFile, _downloadFile, value.paymentStatus),
        endTime: value.endTime ? candid_some(value.endTime) : candid_none(),
        specialRequests: value.specialRequests,
        tripId: value.tripId,
        totalCost: value.totalCost ? candid_some(value.totalCost) : candid_none(),
        distance: value.distance,
        translatorNeeded: value.translatorNeeded,
        endLocation: value.endLocation ? candid_some(value.endLocation) : candid_none(),
        helpLoadingItems: value.helpLoadingItems ? candid_some(value.helpLoadingItems) : candid_none(),
        tripCostCalculation: value.tripCostCalculation ? candid_some(value.tripCostCalculation) : candid_none(),
        startLocation: value.startLocation,
        locationDetails: to_candid_LocationDetails_n14(_uploadFile, _downloadFile, value.locationDetails),
        statusUpdate: value.statusUpdate ? candid_some(to_candid_StatusUpdate_n16(_uploadFile, _downloadFile, value.statusUpdate)) : candid_none(),
        tripStatus: to_candid_TripStatus_n18(_uploadFile, _downloadFile, value.tripStatus),
        depositPaid: value.depositPaid
    };
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dropoffCoordinates?: Coordinates;
    pickupCoordinates?: Coordinates;
    pickupAddress?: string;
    dropoffAddress?: string;
}): {
    dropoffCoordinates: [] | [_Coordinates];
    pickupCoordinates: [] | [_Coordinates];
    pickupAddress: [] | [string];
    dropoffAddress: [] | [string];
} {
    return {
        dropoffCoordinates: value.dropoffCoordinates ? candid_some(value.dropoffCoordinates) : candid_none(),
        pickupCoordinates: value.pickupCoordinates ? candid_some(value.pickupCoordinates) : candid_none(),
        pickupAddress: value.pickupAddress ? candid_some(value.pickupAddress) : candid_none(),
        dropoffAddress: value.dropoffAddress ? candid_some(value.dropoffAddress) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userCoordinates: Coordinates;
    appRole: AppRole;
    isDriver: boolean;
    userId: Principal;
    profileImage?: ExternalBlob;
    name: string;
    phoneNumber: string;
}): Promise<{
    userCoordinates: _Coordinates;
    appRole: _AppRole;
    isDriver: boolean;
    userId: Principal;
    profileImage: [] | [_ExternalBlob];
    name: string;
    phoneNumber: string;
}> {
    return {
        userCoordinates: value.userCoordinates,
        appRole: to_candid_AppRole_n73(_uploadFile, _downloadFile, value.appRole),
        isDriver: value.isDriver,
        userId: value.userId,
        profileImage: value.profileImage ? candid_some(await to_candid_ExternalBlob_n75(_uploadFile, _downloadFile, value.profileImage)) : candid_none(),
        name: value.name,
        phoneNumber: value.phoneNumber
    };
}
async function to_candid_record_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    driverId: Principal;
    stripeAccountId?: string;
    name: string;
    driverCoordinates: Coordinates;
    carNumber: string;
    photo?: ExternalBlob;
}): Promise<{
    driverId: Principal;
    stripeAccountId: [] | [string];
    name: string;
    driverCoordinates: _Coordinates;
    carNumber: string;
    photo: [] | [_ExternalBlob];
}> {
    return {
        driverId: value.driverId,
        stripeAccountId: value.stripeAccountId ? candid_some(value.stripeAccountId) : candid_none(),
        name: value.name,
        driverCoordinates: value.driverCoordinates,
        carNumber: value.carNumber,
        photo: value.photo ? candid_some(await to_candid_ExternalBlob_n75(_uploadFile, _downloadFile, value.photo)) : candid_none()
    };
}
function to_candid_record_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    description: string;
    filePath: string;
    videoType: VideoType;
}): {
    title: string;
    description: string;
    filePath: string;
    videoType: _VideoType;
} {
    return {
        title: value.title,
        description: value.description,
        filePath: value.filePath,
        videoType: to_candid_VideoType_n64(_uploadFile, _downloadFile, value.videoType)
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): {
    pending: null;
} | {
    paid: null;
} | {
    transferred: null;
} {
    return value == PaymentStatus.pending ? {
        pending: null
    } : value == PaymentStatus.paid ? {
        paid: null
    } : value == PaymentStatus.transferred ? {
        transferred: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "cancelled";
    cancelled: {
        reason: string;
    };
} | {
    __kind__: "arrived";
    arrived: {
        message: string;
    };
} | {
    __kind__: "completed";
    completed: {
        summary: CostSummary;
    };
} | {
    __kind__: "waiting";
    waiting: {
        message: string;
    };
} | {
    __kind__: "inProgress";
    inProgress: {
        message: string;
    };
} | {
    __kind__: "enRoute";
    enRoute: {
        message: string;
    };
} | {
    __kind__: "tripAccepted";
    tripAccepted: {
        message: string;
    };
}): {
    cancelled: {
        reason: string;
    };
} | {
    arrived: {
        message: string;
    };
} | {
    completed: {
        summary: _CostSummary;
    };
} | {
    waiting: {
        message: string;
    };
} | {
    inProgress: {
        message: string;
    };
} | {
    enRoute: {
        message: string;
    };
} | {
    tripAccepted: {
        message: string;
    };
} {
    return value.__kind__ === "cancelled" ? {
        cancelled: value.cancelled
    } : value.__kind__ === "arrived" ? {
        arrived: value.arrived
    } : value.__kind__ === "completed" ? {
        completed: value.completed
    } : value.__kind__ === "waiting" ? {
        waiting: value.waiting
    } : value.__kind__ === "inProgress" ? {
        inProgress: value.inProgress
    } : value.__kind__ === "enRoute" ? {
        enRoute: value.enRoute
    } : value.__kind__ === "tripAccepted" ? {
        tripAccepted: value.tripAccepted
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TripStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    accepted: null;
} | {
    inProgress: null;
} {
    return value == TripStatus.cancelled ? {
        cancelled: null
    } : value == TripStatus.pending ? {
        pending: null
    } : value == TripStatus.completed ? {
        completed: null
    } : value == TripStatus.accepted ? {
        accepted: null
    } : value == TripStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VideoType): {
    driverInstructional: null;
} | {
    clientInstructional: null;
} {
    return value == VideoType.driverInstructional ? {
        driverInstructional: null
    } : value == VideoType.clientInstructional ? {
        clientInstructional: null
    } : value;
}
function to_candid_variant_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): {
    customer: null;
} | {
    driver: null;
} {
    return value == AppRole.customer ? {
        customer: null
    } : value == AppRole.driver ? {
        driver: null
    } : value;
}
function to_candid_variant_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
